name: build nodejs pm2
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - nodejs/pm2/**
      - .github/workflows/nodejs_pm2.yml
jobs:
  push:
    name: "yolks:pm2_nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      #- uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nodejs/pm2
          file: ./nodejs/pm2/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jrh-1997/yolks:pm2_nodejs_${{ matrix.tag }}
